"""Replay recorded planner counterfactuals through the live deterministic policy gate.

The public Space has no model or provider credentials. A context-cut trace therefore
separates two evidence classes:

* a recorded model plan and verifier panel output, generated by a local script; and
* a fresh server-side PolicyGate evaluation over those immutable typed records.

No adapter or write-back callback is available from this module.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from typing import Any

from ledgerlens.incident_models import ActionPlan, IncidentContext
from ledgerlens.runtime_factory import build_policy_gate
from ledgerlens.verification import AuthorizationDecision, VerificationPanelResult

JsonObject = dict[str, Any]


class ContextCutTraceError(ValueError):
    """Raised when a recorded trace cannot be safely replayed."""


def typed_plan_fingerprint(plan: ActionPlan) -> str:
    """Return a stable short fingerprint for the exact typed model plan."""

    canonical = json.dumps(
        plan.model_dump(mode="json", by_alias=True),
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def evaluate_context_cut_trace(trace: Mapping[str, Any], scenario_id: str) -> JsonObject:
    """Re-run deterministic authorization for one recorded context/plan pair."""

    if trace.get("candidateOnly") is not True or trace.get("canClaimAGI") is not False:
        raise ContextCutTraceError("context-cut trace claim boundary is invalid")
    if trace.get("externalMutations") is not False:
        raise ContextCutTraceError("context-cut trace must not contain external mutations")

    scenarios = trace.get("scenarios")
    if not isinstance(scenarios, list):
        raise ContextCutTraceError("context-cut scenarios are missing")
    scenario = next(
        (item for item in scenarios if isinstance(item, Mapping) and item.get("id") == scenario_id),
        None,
    )
    if scenario is None:
        raise ContextCutTraceError(f"unknown context-cut scenario: {scenario_id}")
    if scenario.get("error"):
        raise ContextCutTraceError(f"recorded scenario failed closed: {scenario['error']}")

    context = IncidentContext.model_validate(scenario.get("context"))
    plan = ActionPlan.model_validate(scenario.get("plan"))
    verification = VerificationPanelResult.model_validate(scenario.get("verification"))
    recorded_authorization = AuthorizationDecision.model_validate(
        scenario.get("recordedAuthorization")
    )

    action_targets = _string_sequence_map(trace.get("actionTargets"), "actionTargets")
    evidence_contracts = _string_sequence_map(
        trace.get("requiredEvidenceFactIds"),
        "requiredEvidenceFactIds",
    )
    gate = build_policy_gate(
        action_targets,
        required_evidence_fact_ids=evidence_contracts,
        minimum_plan_confidence=0.8,
        minimum_verifier_confidence=0.85,
        quorum=2,
    )
    authorization = gate.authorize(context, plan, verification)

    present_facts = context.fact_ids
    tool_eligibility = []
    for action_type, targets in sorted(action_targets.items()):
        required = frozenset(evidence_contracts.get(action_type, ()))
        missing = tuple(sorted(required - present_facts))
        tool_eligibility.append(
            {
                "actionType": action_type,
                "targets": list(targets),
                "eligibleFromContext": not missing,
                "requiredEvidenceFactIds": sorted(required),
                "missingEvidenceFactIds": list(missing),
            }
        )

    recorded_matches = (
        recorded_authorization.authorized == authorization.authorized
        and recorded_authorization.reason_codes == authorization.reason_codes
        and recorded_authorization.authorized_action_ids == authorization.authorized_action_ids
    )
    return {
        "scenario": {
            "id": scenario.get("id"),
            "label": scenario.get("label"),
            "question": scenario.get("question"),
            "removedFactIds": list(scenario.get("removedFactIds") or []),
            "presentFactIds": sorted(present_facts),
        },
        "recordedModel": {
            "generatedAt": trace.get("generatedAt"),
            "planner": (trace.get("models") or {}).get("planner"),
            "verifiers": list((trace.get("models") or {}).get("verifiers") or []),
            "providerFamilyIndependenceClaimed": False,
            "plannerReRunForScenario": scenario.get("plannerReRunForScenario") is True,
            "verifiersReRunForScenario": False,
            "plan": plan.model_dump(mode="json", by_alias=True),
            "verification": verification.model_dump(mode="json", by_alias=True),
        },
        "livePolicyReplay": {
            "engine": "ledgerlens.verification.PolicyGate",
            "planFingerprint": typed_plan_fingerprint(plan),
            "authorization": authorization.model_dump(mode="json", by_alias=True),
            "matchesRecordedDecision": recorded_matches,
            "toolsExecuted": False,
        },
        "toolEligibility": tool_eligibility,
        "evidenceClass": ("recorded-model-plan-plus-live-deterministic-policy-replay"),
        "networkUsedForThisRequest": False,
        "externalMutations": False,
        "candidateOnly": True,
        "canClaimAGI": False,
    }


def _string_sequence_map(value: Any, label: str) -> dict[str, tuple[str, ...]]:
    if not isinstance(value, Mapping):
        raise ContextCutTraceError(f"{label} is missing")
    result: dict[str, tuple[str, ...]] = {}
    for raw_key, raw_items in value.items():
        key = str(raw_key).strip()
        if not key or not isinstance(raw_items, (list, tuple)):
            raise ContextCutTraceError(f"{label} contains an invalid entry")
        items = tuple(str(item).strip() for item in raw_items)
        if any(not item for item in items):
            raise ContextCutTraceError(f"{label} contains a blank value")
        result[key] = items
    return result


__all__ = [
    "ContextCutTraceError",
    "evaluate_context_cut_trace",
    "typed_plan_fingerprint",
]
